package burp.tabrenamer;

import burp.api.montoya.logging.Logging;

import javax.swing.JTabbedPane;
import javax.swing.SwingUtilities;

/**
 * Decides what the active Repeater tab should be called and applies it.
 *
 * <p>This is the naming policy — when a tab may be renamed, and how a name is made unique.
 * Finding the tab is delegated entirely to {@link RepeaterUiLocator}, which is the only class
 * that knows anything about Burp's Swing structure. If a lookup fails, nothing is renamed and
 * nothing is logged as an error: not renaming leaves Burp exactly as it was.
 *
 * <p>All Swing access happens on the EDT. Callers on other threads (Burp's HTTP thread, for
 * automatic naming) go through {@link #renameActiveTab}, which dispatches.
 */
public final class RepeaterTabTitler {

    private final RepeaterUiLocator locator;
    private final TabNameGenerator nameGenerator;
    private final Logging logging;

    public RepeaterTabTitler(RepeaterUiLocator locator, TabNameGenerator nameGenerator, Logging logging) {
        this.locator = locator;
        this.nameGenerator = nameGenerator;
        this.logging = logging;
    }

    /**
     * Auto-naming entry point: only overwrites a tab whose title still looks auto-generated,
     * so an existing manual (or user-selection-based) rename is never clobbered. Safe to call
     * from any thread; the actual UI work is dispatched onto the EDT.
     */
    public void renameActiveTab(String newName) {
        renameActiveTab(newName, false);
    }

    /**
     * @param force when true (an explicit user action, e.g. "use selection as tab name"),
     *              overwrites the tab's title regardless of its current value.
     */
    public void renameActiveTab(String newName, boolean force) {
        SwingUtilities.invokeLater(() -> renameActiveTabOnEdt(newName, force));
    }

    /**
     * As {@link #renameActiveTab(String, boolean)}, but for callers already on the EDT that need
     * the rename to happen in the same event as their own {@link #activeTabKey()} lookup —
     * otherwise focus could move in between and the rename could land on a different tab than
     * the one whose staged parts were read.
     */
    void renameActiveTabOnEdt(String newName, boolean force) {
        try {
            JTabbedPane pane = locator.focusedRequestTabStrip();
            if (pane == null) {
                return;
            }
            int index = pane.getSelectedIndex();
            if (index < 0) {
                return;
            }
            if (!force && !isAutoGeneratedTitle(pane.getTitleAt(index))) {
                return;
            }
            // Compared against every other tab, but not this one: re-sending in a tab that
            // already holds the name must not turn "api-users" into "api-users (2)" each send.
            pane.setTitleAt(index, nameGenerator.uniqueAmong(newName, locator.titlesOf(pane, index)));
        } catch (Exception e) {
            logging.logToError("repeater-tab-renamer: failed to rename tab", e);
        }
    }

    /**
     * Identity of the Repeater tab a rename right now would target, for callers that need to
     * associate state with "this tab" (see {@link TabNamePartStore}). The Swing component behind
     * the selected tab is used because it stays the same object for that tab's whole life,
     * whereas its index shifts as tabs are closed or dragged.
     *
     * <p>Must be called on the EDT; returns null off it, or when the tab can't be identified.
     * Callers must not retain the result — {@link TabNamePartStore} holds it weakly.
     */
    Object activeTabKey() {
        try {
            JTabbedPane pane = locator.focusedRequestTabStrip();
            if (pane == null || pane.getSelectedIndex() < 0) {
                return null;
            }
            return pane.getComponentAt(pane.getSelectedIndex());
        } catch (Exception e) {
            logging.logToError("repeater-tab-renamer: failed to identify the active Repeater tab", e);
            return null;
        }
    }

    /**
     * Names for a tab that doesn't exist yet (see {@link SendToRepeaterHotKeyHandler}), made
     * unique against the tabs Repeater already has. Falls back to the name unchanged when the
     * existing tabs can't be read.
     */
    String uniqueNewTabName(String base) {
        try {
            return nameGenerator.uniqueAmong(base, locator.repeaterTabTitles());
        } catch (Exception e) {
            logging.logToError("repeater-tab-renamer: failed to check for duplicate tab names", e);
            return base;
        }
    }

    /** Only overwrite titles that still look auto-generated, so a manual rename is never clobbered. */
    private boolean isAutoGeneratedTitle(String currentTitle) {
        if (currentTitle == null) {
            return true;
        }
        String trimmed = currentTitle.trim();
        return trimmed.isEmpty() || trimmed.matches("\\d+") || trimmed.matches("(?i)untitled.*");
    }
}
