package burp.tabrenamer;

import burp.api.montoya.logging.Logging;

import javax.swing.JTabbedPane;
import javax.swing.SwingUtilities;
import java.awt.Component;
import java.awt.Container;
import java.awt.Frame;
import java.awt.KeyboardFocusManager;
import java.util.Set;

/**
 * Renames the currently focused Repeater request tab.
 *
 * <p>Montoya's public API only lets an extension name a tab it creates itself via
 * {@code Repeater.sendToRepeater(request, name)} — there is no supported way to rename a tab
 * that already exists (e.g. one created by "Send to Repeater" from Proxy/Target). To handle
 * that case we walk the Swing hierarchy from the current keyboard-focus owner outward looking
 * for the {@link JTabbedPane} that holds the Repeater request tabs, and retitle its selected
 * tab. This relies on Burp's internal UI structure rather than a documented API, so it's a
 * best-effort heuristic that may need adjusting if a future Burp release changes that structure.
 */
public final class RepeaterTabTitler {

    private static final Set<String> EDITOR_SUBTAB_TITLES = Set.of(
            "pretty", "raw", "hex", "render", "json beautifier", "inspector"
    );

    private static final Set<String> KNOWN_TOOL_TAB_TITLES = Set.of(
            "dashboard", "target", "proxy", "intruder", "repeater", "sequencer",
            "decoder", "comparer", "logger", "organizer", "extensions", "learn",
            "settings", "recorded login replayer", "collaborator", "extender"
    );

    private final Frame suiteFrame;
    private final Logging logging;

    public RepeaterTabTitler(Frame suiteFrame, Logging logging) {
        this.suiteFrame = suiteFrame;
        this.logging = logging;
    }

    /**
     * Auto-naming entry point: only overwrites a tab whose title still looks auto-generated,
     * so an existing manual (or user-selection-based) rename is never clobbered. Safe to call
     * from any thread; the actual UI work is dispatched onto the EDT.
     */
    public void renameActiveTab(String newName) {
        renameActiveTab(newName, false);
    }

    /**
     * @param force when true (an explicit user action, e.g. "use selection as tab name"),
     *              overwrites the tab's title regardless of its current value.
     */
    public void renameActiveTab(String newName, boolean force) {
        SwingUtilities.invokeLater(() -> {
            try {
                doRename(newName, force);
            } catch (Exception e) {
                logging.logToError("repeater-tab-renamer: failed to rename tab", e);
            }
        });
    }

    private void doRename(String newName, boolean force) {
        Component focusOwner = KeyboardFocusManager.getCurrentKeyboardFocusManager().getFocusOwner();
        if (focusOwner == null) {
            return;
        }

        Container current = (focusOwner instanceof Container) ? (Container) focusOwner : focusOwner.getParent();
        while (current != null && current != suiteFrame) {
            if (current instanceof JTabbedPane pane) {
                if (isKnownToolTabStrip(pane)) {
                    // Walked all the way out to the main tool switcher (Proxy/Repeater/...)
                    // without finding a request tab strip — bail rather than risk renaming
                    // the wrong thing.
                    return;
                }
                if (isRequestTabStrip(pane)) {
                    renameSelectedTab(pane, newName, force);
                    return;
                }
            }
            current = current.getParent();
        }
    }

    private boolean isRequestTabStrip(JTabbedPane pane) {
        return pane.getTabCount() > 0
                && !allTitlesIn(pane, EDITOR_SUBTAB_TITLES)
                && !allTitlesIn(pane, KNOWN_TOOL_TAB_TITLES);
    }

    private boolean isKnownToolTabStrip(JTabbedPane pane) {
        return pane.getTabCount() > 0 && allTitlesIn(pane, KNOWN_TOOL_TAB_TITLES);
    }

    private boolean allTitlesIn(JTabbedPane pane, Set<String> candidates) {
        for (int i = 0; i < pane.getTabCount(); i++) {
            String title = pane.getTitleAt(i);
            if (title == null || !candidates.contains(title.trim().toLowerCase())) {
                return false;
            }
        }
        return true;
    }

    private void renameSelectedTab(JTabbedPane pane, String newName, boolean force) {
        int index = pane.getSelectedIndex();
        if (index < 0) {
            return;
        }
        if (force || isAutoGeneratedTitle(pane.getTitleAt(index))) {
            pane.setTitleAt(index, newName);
        }
    }

    /** Only overwrite titles that still look auto-generated, so a manual rename is never clobbered. */
    private boolean isAutoGeneratedTitle(String currentTitle) {
        if (currentTitle == null) {
            return true;
        }
        String trimmed = currentTitle.trim();
        return trimmed.isEmpty() || trimmed.matches("\\d+") || trimmed.matches("(?i)untitled.*");
    }
}
